In [1]:
import urllib
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

### Bramble Cove, TAS

In [2]:
url_tide_BrambleCove = 'http://www.bom.gov.au/australia/tides/print.php?aac=TAS_TP017&type=tide&date=19-11-2020&region=TAS&tz=Australia/Hobart&tz_js=AEDT&days=14'

In [62]:
Long = '146.00'
Lat = '-43.19'

In [3]:
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen

hdr = {'User-Agent': 'Mozilla/5.0'}
req = Request(url_tide_BrambleCove, headers=hdr)

page = urlopen(req)
soup_tide_BrambleCove = BeautifulSoup(page, "lxml")
fout = open('tide_BrambleCove_temp.txt', 'wt', encoding='utf-8')
fout.write(str(soup_tide_BrambleCove)) # save to file
fout.close()

#### Experiment UTC Time Capture

In [99]:
# print(soup_tide_BrambleCove.prettify())

In [5]:
soup_tide_BrambleCove.find_all("td", class_="localtime")

[<td class="localtime high-tide" data-time-local="2020-11-19T03:36:00+11:00" data-time-utc="2020-11-18T16:36:00Z">3:36 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-19T09:33:00+11:00" data-time-utc="2020-11-18T22:33:00Z">9:33 am</td>,
 <td class="localtime high-tide" data-time-local="2020-11-19T12:40:00+11:00" data-time-utc="2020-11-19T01:40:00Z">12:40 pm</td>,
 <td class="localtime low-tide" data-time-local="2020-11-19T20:30:00+11:00" data-time-utc="2020-11-19T09:30:00Z">8:30 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-20T04:15:00+11:00" data-time-utc="2020-11-19T17:15:00Z">4:15 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-20T10:15:00+11:00" data-time-utc="2020-11-19T23:15:00Z">10:15 am</td>,
 <td class="localtime high-tide" data-time-local="2020-11-20T13:03:00+11:00" data-time-utc="2020-11-20T02:03:00Z">1:03 pm</td>,
 <td class="localtime low-tide" data-time-local="2020-11-20T21:06:00+11:00" data-time-utc="2020-11-20T10:06:00Z">9:06 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-21T04:53:00+11:00" data-time-utc="2020-11-20T17:53:00Z">4:53 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-21T21:37:00+11:00" data-time-utc="2020-11-21T10:37:00Z">9:37 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>,
 <td class="localtime high-tide" data-time-local="2020-11-22T05:26:00+11:00" data-time-utc="2020-11-21T18:26:00Z">5:26 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-22T20:18:00+11:00" data-time-utc="2020-11-22T09:18:00Z">8:18 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>,
 <td class="localtime high-tide" data-time-local="2020-11-23T05:51:00+11:00" data-time-utc="2020-11-22T18:51:00Z">5:51 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-23T15:46:00+11:00" data-time-utc="2020-11-23T04:46:00Z">3:46 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>,
 <td class="localtime high-tide" data-time-local="2020-11-24T06:13:00+11:00" data-time-utc="2020-11-23T19:13:00Z">6:13 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-24T15:57:00+11:00" data-time-utc="2020-11-24T04:57:00Z">3:57 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>,
 <td class="localtime high-tide" data-time-local="2020-11-25T06:34:00+11:00" data-time-utc="2020-11-24T19:34:00Z">6:34 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-25T14:07:00+11:00" data-time-utc="2020-11-25T03:07:00Z">2:07 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-25T19:53:00+11:00" data-time-utc="2020-11-25T08:53:00Z">7:53 pm</td>,
 <td class="localtime low-tide" data-time-local="2020-11-25T21:03:00+11:00" data-time-utc="2020-11-25T10:03:00Z">9:03 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-26T06:59:00+11:00" data-time-utc="2020-11-25T19:59:00Z">6:59 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-26T14:17:00+11:00" data-time-utc="2020-11-26T03:17:00Z">2:17 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-26T20:22:00+11:00" data-time-utc="2020-11-26T09:22:00Z">8:22 pm</td>,
 <td class="localtime low-tide" data-time-local="2020-11-26T21:59:00+11:00" data-time-utc="2020-11-26T10:59:00Z">9:59 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-27T04:07:00+11:00" data-time-utc="2020-11-26T17:07:00Z">4:07 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-27T14:35:00+11:00" data-time-utc="2020-11-27T03:35:00Z">2:35 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-27T20:58:00+11:00" data-time-utc="2020-11-27T09:58:00Z">8:58 pm</td>,
 <td class="localtime low-tide" data-time-local="2020-11-27T22:55:00+11:00" data-time-utc="2020-11-27T11:55:00Z">10:55 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-28T04:22:00+11:00" data-time-utc="2020-11-27T17:22:00Z">4:22 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-28T14:56:00+11:00" data-time-utc="2020-11-28T03:56:00Z">2:56 pm</td>,
 <td class="localtime high-tide" data-time-local="2020-11-28T21:58:00+11:00" data-time-utc="2020-11-28T10:58:00Z">9:58 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime low-tide" data-time-local="2020-11-29T15:20:00+11:00" data-time-utc="2020-11-29T04:20:00Z">3:20 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>,
 <td class="localtime high-tide" data-time-local="2020-11-30T01:09:00+11:00" data-time-utc="2020-11-29T14:09:00Z">1:09 am</td>,
 <td class="localtime low-tide" data-time-local="2020-11-30T15:55:00+11:00" data-time-utc="2020-11-30T04:55:00Z">3:55 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>,
 <td class="localtime high-tide" data-time-local="2020-12-01T02:09:00+11:00" data-time-utc="2020-11-30T15:09:00Z">2:09 am</td>,
 <td class="localtime low-tide" data-time-local="2020-12-01T17:15:00+11:00" data-time-utc="2020-12-01T06:15:00Z">5:15 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>,
 <td class="localtime high-tide" data-time-local="2020-12-02T03:08:00+11:00" data-time-utc="2020-12-01T16:08:00Z">3:08 am</td>,
 <td class="localtime low-tide" data-time-local="2020-12-02T18:33:00+11:00" data-time-utc="2020-12-02T07:33:00Z">6:33 pm</td>,
 <td class="localtime"> </td>,
 <td class="localtime"> </td>]

In [6]:
#soup_tide_BrambleCove.find_all('data-time-local')

#for x in soup_tide_BrambleCove.find_all('td'):
#    print(x.get('data-time-local'))
# soup_tide_BrambleCove.find_all("td", class_="localtime")
local_time1 = [x.get('data-time-local') for x in soup_tide_BrambleCove.find_all("td", class_="localtime")]
local_time1

['2020-11-19T03:36:00+11:00',
 '2020-11-19T09:33:00+11:00',
 '2020-11-19T12:40:00+11:00',
 '2020-11-19T20:30:00+11:00',
 '2020-11-20T04:15:00+11:00',
 '2020-11-20T10:15:00+11:00',
 '2020-11-20T13:03:00+11:00',
 '2020-11-20T21:06:00+11:00',
 '2020-11-21T04:53:00+11:00',
 '2020-11-21T21:37:00+11:00',
 None,
 None,
 '2020-11-22T05:26:00+11:00',
 '2020-11-22T20:18:00+11:00',
 None,
 None,
 '2020-11-23T05:51:00+11:00',
 '2020-11-23T15:46:00+11:00',
 None,
 None,
 '2020-11-24T06:13:00+11:00',
 '2020-11-24T15:57:00+11:00',
 None,
 None,
 '2020-11-25T06:34:00+11:00',
 '2020-11-25T14:07:00+11:00',
 '2020-11-25T19:53:00+11:00',
 '2020-11-25T21:03:00+11:00',
 '2020-11-26T06:59:00+11:00',
 '2020-11-26T14:17:00+11:00',
 '2020-11-26T20:22:00+11:00',
 '2020-11-26T21:59:00+11:00',
 '2020-11-27T04:07:00+11:00',
 '2020-11-27T14:35:00+11:00',
 '2020-11-27T20:58:00+11:00',
 '2020-11-27T22:55:00+11:00',
 '2020-11-28T04:22:00+11:00',
 '2020-11-28T14:56:00+11:00',
 '2020-11-28T21:58:00+11:00',
 None,
 '2020-11-29T15:20:00+11:00',
 None,
 None,
 None,
 '2020-11-30T01:09:00+11:00',
 '2020-11-30T15:55:00+11:00',
 None,
 None,
 '2020-12-01T02:09:00+11:00',
 '2020-12-01T17:15:00+11:00',
 None,
 None,
 '2020-12-02T03:08:00+11:00',
 '2020-12-02T18:33:00+11:00',
 None,
 None]

In [7]:
len(local_time1)

56

#### Dates and Tides Info

In [8]:
dates = [h3.text.replace('\n', '') for h3 in soup_tide_BrambleCove.find_all('h3')]
dates

['Thu 19 Nov',
 'Fri 20 Nov',
 'Sat 21 Nov',
 'Sun 22 Nov',
 'Mon 23 Nov',
 'Tue 24 Nov',
 'Wed 25 Nov',
 'Thu 26 Nov',
 'Fri 27 Nov',
 'Sat 28 Nov',
 'Sun 29 Nov',
 'Mon 30 Nov',
 'Tue 1 Dec',
 'Wed 2 Dec']

In [9]:
tables = soup_tide_BrambleCove.find_all('table')
ths = soup_tide_BrambleCove.find_all('th')
rows = list()
for tr in tables:
    rows.append([tr.text.replace('\n', ',').replace('\xa0', '') ] )
rows

[[',,,High,3:36 am,,,1.09 m,,,Low,9:33 am,,,0.61 m,,,High,12:40 pm,,,0.69 m,,,Low,8:30 pm,,,0.06 m,,,'],
 [',,,High,4:15 am,,,1.09 m,,,Low,10:15 am,,,0.59 m,,,High,1:03 pm,,,0.65 m,,,Low,9:06 pm,,,0.12 m,,,'],
 [',,,High,4:53 am,,,1.06 m,,,Low,9:37 pm,,,0.25 m,,,,,,,,,,,,,,,,,'],
 [',,,High,5:26 am,,,1.00 m,,,Low,8:18 pm,,,0.39 m,,,,,,,,,,,,,,,,,'],
 [',,,High,5:51 am,,,0.93 m,,,Low,3:46 pm,,,0.42 m,,,,,,,,,,,,,,,,,'],
 [',,,High,6:13 am,,,0.87 m,,,Low,3:57 pm,,,0.38 m,,,,,,,,,,,,,,,,,'],
 [',,,High,6:34 am,,,0.82 m,,,Low,2:07 pm,,,0.36 m,,,High,7:53 pm,,,0.54 m,,,Low,9:03 pm,,,0.53 m,,,'],
 [',,,High,6:59 am,,,0.77 m,,,Low,2:17 pm,,,0.33 m,,,High,8:22 pm,,,0.57 m,,,Low,9:59 pm,,,0.55 m,,,'],
 [',,,High,4:07 am,,,0.72 m,,,Low,2:35 pm,,,0.31 m,,,High,8:58 pm,,,0.60 m,,,Low,10:55 pm,,,0.57 m,,,'],
 [',,,High,4:22 am,,,0.65 m,,,Low,2:56 pm,,,0.29 m,,,High,9:58 pm,,,0.61 m,,,,,,,,,,'],
 [',,,Low,3:20 pm,,,0.28 m,,,,,,,,,,,,,,,,,,,,,,,,'],
 [',,,High,1:09 am,,,0.66 m,,,Low,3:55 pm,,,0.25 m,,,,,,,,,,,,,,,,,'],
 [',,,High,2:09 am,,,0.74 m,,,Low,5:15 pm,,,0.19 m,,,,,,,,,,,,,,,,,'],
 [',,,High,3:08 am,,,0.83 m,,,Low,6:33 pm,,,0.11 m,,,,,,,,,,,,,,,,,']]

In [10]:
data = np.column_stack((dates, rows))

In [70]:
df = pd.DataFrame(data=data, columns={'Date','Height'})
print(df)

          Date                                             Height
0   Thu 19 Nov  ,,,High,3:36 am,,,1.09 m,,,Low,9:33 am,,,0.61 ...
1   Fri 20 Nov  ,,,High,4:15 am,,,1.09 m,,,Low,10:15 am,,,0.59...
2   Sat 21 Nov  ,,,High,4:53 am,,,1.06 m,,,Low,9:37 pm,,,0.25 ...
3   Sun 22 Nov  ,,,High,5:26 am,,,1.00 m,,,Low,8:18 pm,,,0.39 ...
4   Mon 23 Nov  ,,,High,5:51 am,,,0.93 m,,,Low,3:46 pm,,,0.42 ...
5   Tue 24 Nov  ,,,High,6:13 am,,,0.87 m,,,Low,3:57 pm,,,0.38 ...
6   Wed 25 Nov  ,,,High,6:34 am,,,0.82 m,,,Low,2:07 pm,,,0.36 ...
7   Thu 26 Nov  ,,,High,6:59 am,,,0.77 m,,,Low,2:17 pm,,,0.33 ...
8   Fri 27 Nov  ,,,High,4:07 am,,,0.72 m,,,Low,2:35 pm,,,0.31 ...
9   Sat 28 Nov  ,,,High,4:22 am,,,0.65 m,,,Low,2:56 pm,,,0.29 ...
10  Sun 29 Nov    ,,,Low,3:20 pm,,,0.28 m,,,,,,,,,,,,,,,,,,,,,,,,
11  Mon 30 Nov  ,,,High,1:09 am,,,0.66 m,,,Low,3:55 pm,,,0.25 ...
12   Tue 1 Dec  ,,,High,2:09 am,,,0.74 m,,,Low,5:15 pm,,,0.19 ...
13   Wed 2 Dec  ,,,High,3:08 am,,,0.83 m,,,Low,6:33 pm,,,0.11 ...

In [71]:
df_2 = df['Height'].str.split(',', expand = True)
df_2

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,,,,High,3:36 am,,,1.09 m,,,...,,,Low,8:30 pm,,,0.06 m,,,
1,,,,High,4:15 am,,,1.09 m,,,...,,,Low,9:06 pm,,,0.12 m,,,
2,,,,High,4:53 am,,,1.06 m,,,...,,,,,,,,,,
3,,,,High,5:26 am,,,1.00 m,,,...,,,,,,,,,,
4,,,,High,5:51 am,,,0.93 m,,,...,,,,,,,,,,
5,,,,High,6:13 am,,,0.87 m,,,...,,,,,,,,,,
6,,,,High,6:34 am,,,0.82 m,,,...,,,Low,9:03 pm,,,0.53 m,,,
7,,,,High,6:59 am,,,0.77 m,,,...,,,Low,9:59 pm,,,0.55 m,,,
8,,,,High,4:07 am,,,0.72 m,,,...,,,Low,10:55 pm,,,0.57 m,,,
9,,,,High,4:22 am,,,0.65 m,,,...,,,,,,,,,,
10,,,,Low,3:20 pm,,,0.28 m,,,...,,,,,,,,,,
11,,,,High,1:09 am,,,0.66 m,,,...,,,,,,,,,,
12,,,,High,2:09 am,,,0.74 m,,,...,,,,,,,,,,
13,,,,High,3:08 am,,,0.83 m,,,...,,,,,,,,,,

In [72]:
df_2 = df_2.drop(columns=[0,1,2,5,6,8,9,12,13,15,16,19,20,22,23,26,27,29,30,31])
df_2

,3,4,7,10,11,14,17,18,21,24,25,28
0,High,3:36 am,1.09 m,Low,9:33 am,0.61 m,High,12:40 pm,0.69 m,Low,8:30 pm,0.06 m
1,High,4:15 am,1.09 m,Low,10:15 am,0.59 m,High,1:03 pm,0.65 m,Low,9:06 pm,0.12 m
2,High,4:53 am,1.06 m,Low,9:37 pm,0.25 m,,,,,,
3,High,5:26 am,1.00 m,Low,8:18 pm,0.39 m,,,,,,
4,High,5:51 am,0.93 m,Low,3:46 pm,0.42 m,,,,,,
5,High,6:13 am,0.87 m,Low,3:57 pm,0.38 m,,,,,,
6,High,6:34 am,0.82 m,Low,2:07 pm,0.36 m,High,7:53 pm,0.54 m,Low,9:03 pm,0.53 m
7,High,6:59 am,0.77 m,Low,2:17 pm,0.33 m,High,8:22 pm,0.57 m,Low,9:59 pm,0.55 m
8,High,4:07 am,0.72 m,Low,2:35 pm,0.31 m,High,8:58 pm,0.60 m,Low,10:55 pm,0.57 m
9,High,4:22 am,0.65 m,Low,2:56 pm,0.29 m,High,9:58 pm,0.61 m,,,
10,Low,3:20 pm,0.28 m,,,,,,,,,
11,High,1:09 am,0.66 m,Low,3:55 pm,0.25 m,,,,,,
12,High,2:09 am,0.74 m,Low,5:15 pm,0.19 m,,,,,,
13,High,3:08 am,0.83 m,Low,6:33 pm,0.11 m,,,,,,

In [73]:
df_3 = pd.concat([df['Date'] ,df_2], axis=1)
df_3

,Date,3,4,7,10,11,14,17,18,21,24,25,28
0,Thu 19 Nov,High,3:36 am,1.09 m,Low,9:33 am,0.61 m,High,12:40 pm,0.69 m,Low,8:30 pm,0.06 m
1,Fri 20 Nov,High,4:15 am,1.09 m,Low,10:15 am,0.59 m,High,1:03 pm,0.65 m,Low,9:06 pm,0.12 m
2,Sat 21 Nov,High,4:53 am,1.06 m,Low,9:37 pm,0.25 m,,,,,,
3,Sun 22 Nov,High,5:26 am,1.00 m,Low,8:18 pm,0.39 m,,,,,,
4,Mon 23 Nov,High,5:51 am,0.93 m,Low,3:46 pm,0.42 m,,,,,,
5,Tue 24 Nov,High,6:13 am,0.87 m,Low,3:57 pm,0.38 m,,,,,,
6,Wed 25 Nov,High,6:34 am,0.82 m,Low,2:07 pm,0.36 m,High,7:53 pm,0.54 m,Low,9:03 pm,0.53 m
7,Thu 26 Nov,High,6:59 am,0.77 m,Low,2:17 pm,0.33 m,High,8:22 pm,0.57 m,Low,9:59 pm,0.55 m
8,Fri 27 Nov,High,4:07 am,0.72 m,Low,2:35 pm,0.31 m,High,8:58 pm,0.60 m,Low,10:55 pm,0.57 m
9,Sat 28 Nov,High,4:22 am,0.65 m,Low,2:56 pm,0.29 m,High,9:58 pm,0.61 m,,,
10,Sun 29 Nov,Low,3:20 pm,0.28 m,,,,,,,,,
11,Mon 30 Nov,High,1:09 am,0.66 m,Low,3:55 pm,0.25 m,,,,,,
12,Tue 1 Dec,High,2:09 am,0.74 m,Low,5:15 pm,0.19 m,,,,,,
13,Wed 2 Dec,High,3:08 am,0.83 m,Low,6:33 pm,0.11 m,,,,,,

In [74]:
df_3 = df_3.rename(columns={'1':'Date', 3: 'High_1', 4: 'High_Time_1', 7: 'High_Height_1',
                    10: 'Low_1', 11: 'Low_Time_1', 14: 'Low_Height_1',
                    17: 'High_2', 18: 'High_Time_2', 21: 'High_Height_2',
                    24: 'Low_2', 25: 'Low_Time_2', 28: 'Low_Height_2',})
df_3

,Date,High_1,High_Time_1,High_Height_1,Low_1,Low_Time_1,Low_Height_1,High_2,High_Time_2,High_Height_2,Low_2,Low_Time_2,Low_Height_2
0,Thu 19 Nov,High,3:36 am,1.09 m,Low,9:33 am,0.61 m,High,12:40 pm,0.69 m,Low,8:30 pm,0.06 m
1,Fri 20 Nov,High,4:15 am,1.09 m,Low,10:15 am,0.59 m,High,1:03 pm,0.65 m,Low,9:06 pm,0.12 m
2,Sat 21 Nov,High,4:53 am,1.06 m,Low,9:37 pm,0.25 m,,,,,,
3,Sun 22 Nov,High,5:26 am,1.00 m,Low,8:18 pm,0.39 m,,,,,,
4,Mon 23 Nov,High,5:51 am,0.93 m,Low,3:46 pm,0.42 m,,,,,,
5,Tue 24 Nov,High,6:13 am,0.87 m,Low,3:57 pm,0.38 m,,,,,,
6,Wed 25 Nov,High,6:34 am,0.82 m,Low,2:07 pm,0.36 m,High,7:53 pm,0.54 m,Low,9:03 pm,0.53 m
7,Thu 26 Nov,High,6:59 am,0.77 m,Low,2:17 pm,0.33 m,High,8:22 pm,0.57 m,Low,9:59 pm,0.55 m
8,Fri 27 Nov,High,4:07 am,0.72 m,Low,2:35 pm,0.31 m,High,8:58 pm,0.60 m,Low,10:55 pm,0.57 m
9,Sat 28 Nov,High,4:22 am,0.65 m,Low,2:56 pm,0.29 m,High,9:58 pm,0.61 m,,,
10,Sun 29 Nov,Low,3:20 pm,0.28 m,,,,,,,,,
11,Mon 30 Nov,High,1:09 am,0.66 m,Low,3:55 pm,0.25 m,,,,,,
12,Tue 1 Dec,High,2:09 am,0.74 m,Low,5:15 pm,0.19 m,,,,,,
13,Wed 2 Dec,High,3:08 am,0.83 m,Low,6:33 pm,0.11 m,,,,,,

### Location Name and State

In [75]:
location_name = soup_tide_BrambleCove.h2.text.split(' \xa0–\xa0')[0].split(', ')[0]
state = soup_tide_BrambleCove.h2.text.split(' \xa0–\xa0')[0].split(', ')[1]
print(location_name, state)

Bramble Cove TAS

In [76]:
df_3 = df_3.assign(Location=location_name, State=state, Long=Long, Lat=Lat)
df_3

,Date,High_1,High_Time_1,High_Height_1,Low_1,Low_Time_1,Low_Height_1,High_2,High_Time_2,High_Height_2,Low_2,Low_Time_2,Low_Height_2,Location,State,Long,Lat
0,Thu 19 Nov,High,3:36 am,1.09 m,Low,9:33 am,0.61 m,High,12:40 pm,0.69 m,Low,8:30 pm,0.06 m,Bramble Cove,TAS,146.00,-43.19
1,Fri 20 Nov,High,4:15 am,1.09 m,Low,10:15 am,0.59 m,High,1:03 pm,0.65 m,Low,9:06 pm,0.12 m,Bramble Cove,TAS,146.00,-43.19
2,Sat 21 Nov,High,4:53 am,1.06 m,Low,9:37 pm,0.25 m,,,,,,,Bramble Cove,TAS,146.00,-43.19
3,Sun 22 Nov,High,5:26 am,1.00 m,Low,8:18 pm,0.39 m,,,,,,,Bramble Cove,TAS,146.00,-43.19
4,Mon 23 Nov,High,5:51 am,0.93 m,Low,3:46 pm,0.42 m,,,,,,,Bramble Cove,TAS,146.00,-43.19
5,Tue 24 Nov,High,6:13 am,0.87 m,Low,3:57 pm,0.38 m,,,,,,,Bramble Cove,TAS,146.00,-43.19
6,Wed 25 Nov,High,6:34 am,0.82 m,Low,2:07 pm,0.36 m,High,7:53 pm,0.54 m,Low,9:03 pm,0.53 m,Bramble Cove,TAS,146.00,-43.19
7,Thu 26 Nov,High,6:59 am,0.77 m,Low,2:17 pm,0.33 m,High,8:22 pm,0.57 m,Low,9:59 pm,0.55 m,Bramble Cove,TAS,146.00,-43.19
8,Fri 27 Nov,High,4:07 am,0.72 m,Low,2:35 pm,0.31 m,High,8:58 pm,0.60 m,Low,10:55 pm,0.57 m,Bramble Cove,TAS,146.00,-43.19
9,Sat 28 Nov,High,4:22 am,0.65 m,Low,2:56 pm,0.29 m,High,9:58 pm,0.61 m,,,,Bramble Cove,TAS,146.00,-43.19
10,Sun 29 Nov,Low,3:20 pm,0.28 m,,,,,,,,,,Bramble Cove,TAS,146.00,-43.19
11,Mon 30 Nov,High,1:09 am,0.66 m,Low,3:55 pm,0.25 m,,,,,,,Bramble Cove,TAS,146.00,-43.19
12,Tue 1 Dec,High,2:09 am,0.74 m,Low,5:15 pm,0.19 m,,,,,,,Bramble Cove,TAS,146.00,-43.19
13,Wed 2 Dec,High,3:08 am,0.83 m,Low,6:33 pm,0.11 m,,,,,,,Bramble Cove,TAS,146.00,-43.19

In [77]:
df_3.to_csv(r'./1128_raw_bs4_tides.csv', index = False, mode='a', header=True)

In [56]:
# df.to_csv(r'./1119raw_bs4_tides.csv', index = False, header=True)

#### Reshape and add UTC local time

In [78]:
df = pd.read_csv('./1128_raw_bs4_tides.csv')
df.head()

,Date,High_1,High_Time_1,High_Height_1,Low_1,Low_Time_1,Low_Height_1,High_2,High_Time_2,High_Height_2,Low_2,Low_Time_2,Low_Height_2,Location,State,Long,Lat
0,Thu 19 Nov,High,3:36 am,1.09 m,Low,9:33 am,0.61 m,High,12:40 pm,0.69 m,Low,8:30 pm,0.06 m,Bramble Cove,TAS,146.0,-43.19
1,Fri 20 Nov,High,4:15 am,1.09 m,Low,10:15 am,0.59 m,High,1:03 pm,0.65 m,Low,9:06 pm,0.12 m,Bramble Cove,TAS,146.0,-43.19
2,Sat 21 Nov,High,4:53 am,1.06 m,Low,9:37 pm,0.25 m,NaN,NaN,NaN,NaN,NaN,NaN,Bramble Cove,TAS,146.0,-43.19
3,Sun 22 Nov,High,5:26 am,1.00 m,Low,8:18 pm,0.39 m,NaN,NaN,NaN,NaN,NaN,NaN,Bramble Cove,TAS,146.0,-43.19
4,Mon 23 Nov,High,5:51 am,0.93 m,Low,3:46 pm,0.42 m,NaN,NaN,NaN,NaN,NaN,NaN,Bramble Cove,TAS,146.0,-43.19

In [79]:
df.stack(dropna=True)

0   Date               Thu 19 Nov
    High_1                   High
    High_Time_1           3:36 am
    High_Height_1          1.09 m
    Low_1                     Low
                         ...
13  Low_Height_1           0.11 m
    Location         Bramble Cove
    State                     TAS
    Long                      146
    Lat                    -43.19
Length: 184, dtype: object

In [80]:
df1 = df[['Date','High_1','High_Time_1','High_Height_1','Location','Long','Lat','State']]
# df1

In [81]:
df2 = df[['Date','Low_1','Low_Time_1','Low_Height_1','Location','Long','Lat','State']]
#df2

In [82]:
df3 = df[['Date','High_2','High_Time_2','High_Height_2','Location','Long','Lat','State']]
#df3

In [83]:
df4 = df[['Date','Low_2','Low_Time_2','Low_Height_2','Location','Long','Lat','State']]
#df4

In [84]:
df.columns

Index(['Date', 'High_1', 'High_Time_1', 'High_Height_1', 'Low_1', 'Low_Time_1',
       'Low_Height_1', 'High_2', 'High_Time_2', 'High_Height_2', 'Low_2',
       'Low_Time_2', 'Low_Height_2', 'Location', 'State', 'Long', 'Lat'],
      dtype='object')

In [85]:
df1 = df1.rename(columns = {'Date':'Date','High_1':'Type','High_Time_1':'Time','High_Height_1':'Height', 
                      4:'Location',5:'Long',6:'Lat',7:'State'})
#df1

In [86]:
df2 = df2.rename(columns = {'Date':'Date','Low_1':'Type','Low_Time_1':'Time','Low_Height_1':'Height', 
                      4:'Location',5:'Long',6:'Lat',7:'State'})
#df2

In [87]:
df3 = df3.rename(columns = {'Date':'Date','High_2':'Type','High_Time_2':'Time',
                            'High_Height_2':'Height', 
                      4:'Location',5:'Long',6:'Lat',7:'State'})
#df3

In [88]:
df4 = df4.rename(columns = {'Date':'Date','Low_2':'Type','Low_Time_2':'Time','Low_Height_2':'Height', 
                      4:'Location',5:'Long',6:'Lat',7:'State'})
#df4

In [89]:
df_time = pd.DataFrame(local_time1,
                   columns=['local_time'])
df_time

                   local_time
0   2020-11-19T03:36:00+11:00
1   2020-11-19T09:33:00+11:00
2   2020-11-19T12:40:00+11:00
3   2020-11-19T20:30:00+11:00
4   2020-11-20T04:15:00+11:00
5   2020-11-20T10:15:00+11:00
6   2020-11-20T13:03:00+11:00
7   2020-11-20T21:06:00+11:00
8   2020-11-21T04:53:00+11:00
9   2020-11-21T21:37:00+11:00
10                       None
11                       None
12  2020-11-22T05:26:00+11:00
13  2020-11-22T20:18:00+11:00
14                       None
15                       None
16  2020-11-23T05:51:00+11:00
17  2020-11-23T15:46:00+11:00
18                       None
19                       None
20  2020-11-24T06:13:00+11:00
21  2020-11-24T15:57:00+11:00
22                       None
23                       None
24  2020-11-25T06:34:00+11:00
25  2020-11-25T14:07:00+11:00
26  2020-11-25T19:53:00+11:00
27  2020-11-25T21:03:00+11:00
28  2020-11-26T06:59:00+11:00
29  2020-11-26T14:17:00+11:00
30  2020-11-26T20:22:00+11:00
31  2020-11-26T21:59:00+11:00
32  2020-11-27T04:07:00+11:00
33  2020-11-27T14:35:00+11:00
34  2020-11-27T20:58:00+11:00
35  2020-11-27T22:55:00+11:00
36  2020-11-28T04:22:00+11:00
37  2020-11-28T14:56:00+11:00
38  2020-11-28T21:58:00+11:00
39                       None
40  2020-11-29T15:20:00+11:00
41                       None
42                       None
43                       None
44  2020-11-30T01:09:00+11:00
45  2020-11-30T15:55:00+11:00
46                       None
47                       None
48  2020-12-01T02:09:00+11:00
49  2020-12-01T17:15:00+11:00
50                       None
51                       None
52  2020-12-02T03:08:00+11:00
53  2020-12-02T18:33:00+11:00
54                       None
55                       None

In [90]:
df_time = pd.DataFrame(np.reshape(df_time.values,(14,4)), 
                    columns=['time1','time2','time3','time4'])
df_time

,time1,time2,time3,time4
0,2020-11-19T03:36:00+11:00,2020-11-19T09:33:00+11:00,2020-11-19T12:40:00+11:00,2020-11-19T20:30:00+11:00
1,2020-11-20T04:15:00+11:00,2020-11-20T10:15:00+11:00,2020-11-20T13:03:00+11:00,2020-11-20T21:06:00+11:00
2,2020-11-21T04:53:00+11:00,2020-11-21T21:37:00+11:00,None,None
3,2020-11-22T05:26:00+11:00,2020-11-22T20:18:00+11:00,None,None
4,2020-11-23T05:51:00+11:00,2020-11-23T15:46:00+11:00,None,None
5,2020-11-24T06:13:00+11:00,2020-11-24T15:57:00+11:00,None,None
6,2020-11-25T06:34:00+11:00,2020-11-25T14:07:00+11:00,2020-11-25T19:53:00+11:00,2020-11-25T21:03:00+11:00
7,2020-11-26T06:59:00+11:00,2020-11-26T14:17:00+11:00,2020-11-26T20:22:00+11:00,2020-11-26T21:59:00+11:00
8,2020-11-27T04:07:00+11:00,2020-11-27T14:35:00+11:00,2020-11-27T20:58:00+11:00,2020-11-27T22:55:00+11:00
9,2020-11-28T04:22:00+11:00,2020-11-28T14:56:00+11:00,2020-11-28T21:58:00+11:00,None
10,2020-11-29T15:20:00+11:00,None,None,None
11,2020-11-30T01:09:00+11:00,2020-11-30T15:55:00+11:00,None,None
12,2020-12-01T02:09:00+11:00,2020-12-01T17:15:00+11:00,None,None
13,2020-12-02T03:08:00+11:00,2020-12-02T18:33:00+11:00,None,None

In [92]:
df_time1 = pd.DataFrame(df_time['time1'].values, columns=['time'])
df_time2 = pd.DataFrame(df_time['time2'].values, columns=['time'])
df_time3 = pd.DataFrame(df_time['time3'].values, columns=['time'])
df_time4 = pd.DataFrame(df_time['time4'].values, columns=['time'])
#,df_time['time2'],df_time['time3'],df_time['time4']

In [93]:
df_all_time = pd.concat([df_time1,df_time2,df_time3,df_time4])

In [94]:
clean_df = pd.concat([df1,df2,df3,df4])
clean_df

          Date  Type      Time  Height      Location   Long    Lat State
0   Thu 19 Nov  High   3:36 am  1.09 m  Bramble Cove  146.0 -43.19   TAS
1   Fri 20 Nov  High   4:15 am  1.09 m  Bramble Cove  146.0 -43.19   TAS
2   Sat 21 Nov  High   4:53 am  1.06 m  Bramble Cove  146.0 -43.19   TAS
3   Sun 22 Nov  High   5:26 am  1.00 m  Bramble Cove  146.0 -43.19   TAS
4   Mon 23 Nov  High   5:51 am  0.93 m  Bramble Cove  146.0 -43.19   TAS
5   Tue 24 Nov  High   6:13 am  0.87 m  Bramble Cove  146.0 -43.19   TAS
6   Wed 25 Nov  High   6:34 am  0.82 m  Bramble Cove  146.0 -43.19   TAS
7   Thu 26 Nov  High   6:59 am  0.77 m  Bramble Cove  146.0 -43.19   TAS
8   Fri 27 Nov  High   4:07 am  0.72 m  Bramble Cove  146.0 -43.19   TAS
9   Sat 28 Nov  High   4:22 am  0.65 m  Bramble Cove  146.0 -43.19   TAS
10  Sun 29 Nov   Low   3:20 pm  0.28 m  Bramble Cove  146.0 -43.19   TAS
11  Mon 30 Nov  High   1:09 am  0.66 m  Bramble Cove  146.0 -43.19   TAS
12   Tue 1 Dec  High   2:09 am  0.74 m  Bramble Cove  146.0 -43.19   TAS
13   Wed 2 Dec  High   3:08 am  0.83 m  Bramble Cove  146.0 -43.19   TAS
0   Thu 19 Nov   Low   9:33 am  0.61 m  Bramble Cove  146.0 -43.19   TAS
1   Fri 20 Nov   Low  10:15 am  0.59 m  Bramble Cove  146.0 -43.19   TAS
2   Sat 21 Nov   Low   9:37 pm  0.25 m  Bramble Cove  146.0 -43.19   TAS
3   Sun 22 Nov   Low   8:18 pm  0.39 m  Bramble Cove  146.0 -43.19   TAS
4   Mon 23 Nov   Low   3:46 pm  0.42 m  Bramble Cove  146.0 -43.19   TAS
5   Tue 24 Nov   Low   3:57 pm  0.38 m  Bramble Cove  146.0 -43.19   TAS
6   Wed 25 Nov   Low   2:07 pm  0.36 m  Bramble Cove  146.0 -43.19   TAS
7   Thu 26 Nov   Low   2:17 pm  0.33 m  Bramble Cove  146.0 -43.19   TAS
8   Fri 27 Nov   Low   2:35 pm  0.31 m  Bramble Cove  146.0 -43.19   TAS
9   Sat 28 Nov   Low   2:56 pm  0.29 m  Bramble Cove  146.0 -43.19   TAS
10  Sun 29 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
11  Mon 30 Nov   Low   3:55 pm  0.25 m  Bramble Cove  146.0 -43.19   TAS
12   Tue 1 Dec   Low   5:15 pm  0.19 m  Bramble Cove  146.0 -43.19   TAS
13   Wed 2 Dec   Low   6:33 pm  0.11 m  Bramble Cove  146.0 -43.19   TAS
0   Thu 19 Nov  High  12:40 pm  0.69 m  Bramble Cove  146.0 -43.19   TAS
1   Fri 20 Nov  High   1:03 pm  0.65 m  Bramble Cove  146.0 -43.19   TAS
2   Sat 21 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
3   Sun 22 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
4   Mon 23 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
5   Tue 24 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
6   Wed 25 Nov  High   7:53 pm  0.54 m  Bramble Cove  146.0 -43.19   TAS
7   Thu 26 Nov  High   8:22 pm  0.57 m  Bramble Cove  146.0 -43.19   TAS
8   Fri 27 Nov  High   8:58 pm  0.60 m  Bramble Cove  146.0 -43.19   TAS
9   Sat 28 Nov  High   9:58 pm  0.61 m  Bramble Cove  146.0 -43.19   TAS
10  Sun 29 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
11  Mon 30 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
12   Tue 1 Dec   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
13   Wed 2 Dec   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
0   Thu 19 Nov   Low   8:30 pm  0.06 m  Bramble Cove  146.0 -43.19   TAS
1   Fri 20 Nov   Low   9:06 pm  0.12 m  Bramble Cove  146.0 -43.19   TAS
2   Sat 21 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
3   Sun 22 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
4   Mon 23 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
5   Tue 24 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
6   Wed 25 Nov   Low   9:03 pm  0.53 m  Bramble Cove  146.0 -43.19   TAS
7   Thu 26 Nov   Low   9:59 pm  0.55 m  Bramble Cove  146.0 -43.19   TAS
8   Fri 27 Nov   Low  10:55 pm  0.57 m  Bramble Cove  146.0 -43.19   TAS
9   Sat 28 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
10  Sun 29 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
11  Mon 30 Nov   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
12   Tue 1 Dec   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS
13   Wed 2 Dec   NaN       NaN     NaN  Bramble Cove  146.0 -43.19   TAS

In [95]:
clean_df['Local_time'] = df_all_time
clean_df

,Date,Type,Time,Height,Location,Long,Lat,State,Local_time
0,Thu 19 Nov,High,3:36 am,1.09 m,Bramble Cove,146.0,-43.19,TAS,2020-11-19T03:36:00+11:00
1,Fri 20 Nov,High,4:15 am,1.09 m,Bramble Cove,146.0,-43.19,TAS,2020-11-20T04:15:00+11:00
2,Sat 21 Nov,High,4:53 am,1.06 m,Bramble Cove,146.0,-43.19,TAS,2020-11-21T04:53:00+11:00
3,Sun 22 Nov,High,5:26 am,1.00 m,Bramble Cove,146.0,-43.19,TAS,2020-11-22T05:26:00+11:00
4,Mon 23 Nov,High,5:51 am,0.93 m,Bramble Cove,146.0,-43.19,TAS,2020-11-23T05:51:00+11:00
5,Tue 24 Nov,High,6:13 am,0.87 m,Bramble Cove,146.0,-43.19,TAS,2020-11-24T06:13:00+11:00
6,Wed 25 Nov,High,6:34 am,0.82 m,Bramble Cove,146.0,-43.19,TAS,2020-11-25T06:34:00+11:00
7,Thu 26 Nov,High,6:59 am,0.77 m,Bramble Cove,146.0,-43.19,TAS,2020-11-26T06:59:00+11:00
8,Fri 27 Nov,High,4:07 am,0.72 m,Bramble Cove,146.0,-43.19,TAS,2020-11-27T04:07:00+11:00
9,Sat 28 Nov,High,4:22 am,0.65 m,Bramble Cove,146.0,-43.19,TAS,2020-11-28T04:22:00+11:00
10,Sun 29 Nov,Low,3:20 pm,0.28 m,Bramble Cove,146.0,-43.19,TAS,2020-11-29T15:20:00+11:00
11,Mon 30 Nov,High,1:09 am,0.66 m,Bramble Cove,146.0,-43.19,TAS,2020-11-30T01:09:00+11:00
12,Tue 1 Dec,High,2:09 am,0.74 m,Bramble Cove,146.0,-43.19,TAS,2020-12-01T02:09:00+11:00
13,Wed 2 Dec,High,3:08 am,0.83 m,Bramble Cove,146.0,-43.19,TAS,2020-12-02T03:08:00+11:00
0,Thu 19 Nov,Low,9:33 am,0.61 m,Bramble Cove,146.0,-43.19,TAS,2020-11-19T09:33:00+11:00
1,Fri 20 Nov,Low,10:15 am,0.59 m,Bramble Cove,146.0,-43.19,TAS,2020-11-20T10:15:00+11:00
2,Sat 21 Nov,Low,9:37 pm,0.25 m,Bramble Cove,146.0,-43.19,TAS,2020-11-21T21:37:00+11:00
3,Sun 22 Nov,Low,8:18 pm,0.39 m,Bramble Cove,146.0,-43.19,TAS,2020-11-22T20:18:00+11:00
4,Mon 23 Nov,Low,3:46 pm,0.42 m,Bramble Cove,146.0,-43.19,TAS,2020-11-23T15:46:00+11:00
5,Tue 24 Nov,Low,3:57 pm,0.38 m,Bramble Cove,146.0,-43.19,TAS,2020-11-24T15:57:00+11:00
6,Wed 25 Nov,Low,2:07 pm,0.36 m,Bramble Cove,146.0,-43.19,TAS,2020-11-25T14:07:00+11:00
7,Thu 26 Nov,Low,2:17 pm,0.33 m,Bramble Cove,146.0,-43.19,TAS,2020-11-26T14:17:00+11:00
8,Fri 27 Nov,Low,2:35 pm,0.31 m,Bramble Cove,146.0,-43.19,TAS,2020-11-27T14:35:00+11:00
9,Sat 28 Nov,Low,2:56 pm,0.29 m,Bramble Cove,146.0,-43.19,TAS,2020-11-28T14:56:00+11:00
10,Sun 29 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
11,Mon 30 Nov,Low,3:55 pm,0.25 m,Bramble Cove,146.0,-43.19,TAS,2020-11-30T15:55:00+11:00
12,Tue 1 Dec,Low,5:15 pm,0.19 m,Bramble Cove,146.0,-43.19,TAS,2020-12-01T17:15:00+11:00
13,Wed 2 Dec,Low,6:33 pm,0.11 m,Bramble Cove,146.0,-43.19,TAS,2020-12-02T18:33:00+11:00
0,Thu 19 Nov,High,12:40 pm,0.69 m,Bramble Cove,146.0,-43.19,TAS,2020-11-19T12:40:00+11:00
1,Fri 20 Nov,High,1:03 pm,0.65 m,Bramble Cove,146.0,-43.19,TAS,2020-11-20T13:03:00+11:00
2,Sat 21 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
3,Sun 22 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
4,Mon 23 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
5,Tue 24 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
6,Wed 25 Nov,High,7:53 pm,0.54 m,Bramble Cove,146.0,-43.19,TAS,2020-11-25T19:53:00+11:00
7,Thu 26 Nov,High,8:22 pm,0.57 m,Bramble Cove,146.0,-43.19,TAS,2020-11-26T20:22:00+11:00
8,Fri 27 Nov,High,8:58 pm,0.60 m,Bramble Cove,146.0,-43.19,TAS,2020-11-27T20:58:00+11:00
9,Sat 28 Nov,High,9:58 pm,0.61 m,Bramble Cove,146.0,-43.19,TAS,2020-11-28T21:58:00+11:00
10,Sun 29 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
11,Mon 30 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
12,Tue 1 Dec,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
13,Wed 2 Dec,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
0,Thu 19 Nov,Low,8:30 pm,0.06 m,Bramble Cove,146.0,-43.19,TAS,2020-11-19T20:30:00+11:00
1,Fri 20 Nov,Low,9:06 pm,0.12 m,Bramble Cove,146.0,-43.19,TAS,2020-11-20T21:06:00+11:00
2,Sat 21 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
3,Sun 22 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
4,Mon 23 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
5,Tue 24 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
6,Wed 25 Nov,Low,9:03 pm,0.53 m,Bramble Cove,146.0,-43.19,TAS,2020-11-25T21:03:00+11:00
7,Thu 26 Nov,Low,9:59 pm,0.55 m,Bramble Cove,146.0,-43.19,TAS,2020-11-26T21:59:00+11:00
8,Fri 27 Nov,Low,10:55 pm,0.57 m,Bramble Cove,146.0,-43.19,TAS,2020-11-27T22:55:00+11:00
9,Sat 28 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
10,Sun 29 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
11,Mon 30 Nov,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
12,Tue 1 Dec,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None
13,Wed 2 Dec,NaN,NaN,NaN,Bramble Cove,146.0,-43.19,TAS,None

In [96]:
clean_df.dropna(inplace=True)
clean_df

,Date,Type,Time,Height,Location,Long,Lat,State,Local_time
0,Thu 19 Nov,High,3:36 am,1.09 m,Bramble Cove,146.0,-43.19,TAS,2020-11-19T03:36:00+11:00
1,Fri 20 Nov,High,4:15 am,1.09 m,Bramble Cove,146.0,-43.19,TAS,2020-11-20T04:15:00+11:00
2,Sat 21 Nov,High,4:53 am,1.06 m,Bramble Cove,146.0,-43.19,TAS,2020-11-21T04:53:00+11:00
3,Sun 22 Nov,High,5:26 am,1.00 m,Bramble Cove,146.0,-43.19,TAS,2020-11-22T05:26:00+11:00
4,Mon 23 Nov,High,5:51 am,0.93 m,Bramble Cove,146.0,-43.19,TAS,2020-11-23T05:51:00+11:00
5,Tue 24 Nov,High,6:13 am,0.87 m,Bramble Cove,146.0,-43.19,TAS,2020-11-24T06:13:00+11:00
6,Wed 25 Nov,High,6:34 am,0.82 m,Bramble Cove,146.0,-43.19,TAS,2020-11-25T06:34:00+11:00
7,Thu 26 Nov,High,6:59 am,0.77 m,Bramble Cove,146.0,-43.19,TAS,2020-11-26T06:59:00+11:00
8,Fri 27 Nov,High,4:07 am,0.72 m,Bramble Cove,146.0,-43.19,TAS,2020-11-27T04:07:00+11:00
9,Sat 28 Nov,High,4:22 am,0.65 m,Bramble Cove,146.0,-43.19,TAS,2020-11-28T04:22:00+11:00
10,Sun 29 Nov,Low,3:20 pm,0.28 m,Bramble Cove,146.0,-43.19,TAS,2020-11-29T15:20:00+11:00
11,Mon 30 Nov,High,1:09 am,0.66 m,Bramble Cove,146.0,-43.19,TAS,2020-11-30T01:09:00+11:00
12,Tue 1 Dec,High,2:09 am,0.74 m,Bramble Cove,146.0,-43.19,TAS,2020-12-01T02:09:00+11:00
13,Wed 2 Dec,High,3:08 am,0.83 m,Bramble Cove,146.0,-43.19,TAS,2020-12-02T03:08:00+11:00
0,Thu 19 Nov,Low,9:33 am,0.61 m,Bramble Cove,146.0,-43.19,TAS,2020-11-19T09:33:00+11:00
1,Fri 20 Nov,Low,10:15 am,0.59 m,Bramble Cove,146.0,-43.19,TAS,2020-11-20T10:15:00+11:00
2,Sat 21 Nov,Low,9:37 pm,0.25 m,Bramble Cove,146.0,-43.19,TAS,2020-11-21T21:37:00+11:00
3,Sun 22 Nov,Low,8:18 pm,0.39 m,Bramble Cove,146.0,-43.19,TAS,2020-11-22T20:18:00+11:00
4,Mon 23 Nov,Low,3:46 pm,0.42 m,Bramble Cove,146.0,-43.19,TAS,2020-11-23T15:46:00+11:00
5,Tue 24 Nov,Low,3:57 pm,0.38 m,Bramble Cove,146.0,-43.19,TAS,2020-11-24T15:57:00+11:00
6,Wed 25 Nov,Low,2:07 pm,0.36 m,Bramble Cove,146.0,-43.19,TAS,2020-11-25T14:07:00+11:00
7,Thu 26 Nov,Low,2:17 pm,0.33 m,Bramble Cove,146.0,-43.19,TAS,2020-11-26T14:17:00+11:00
8,Fri 27 Nov,Low,2:35 pm,0.31 m,Bramble Cove,146.0,-43.19,TAS,2020-11-27T14:35:00+11:00
9,Sat 28 Nov,Low,2:56 pm,0.29 m,Bramble Cove,146.0,-43.19,TAS,2020-11-28T14:56:00+11:00
11,Mon 30 Nov,Low,3:55 pm,0.25 m,Bramble Cove,146.0,-43.19,TAS,2020-11-30T15:55:00+11:00
12,Tue 1 Dec,Low,5:15 pm,0.19 m,Bramble Cove,146.0,-43.19,TAS,2020-12-01T17:15:00+11:00
13,Wed 2 Dec,Low,6:33 pm,0.11 m,Bramble Cove,146.0,-43.19,TAS,2020-12-02T18:33:00+11:00
0,Thu 19 Nov,High,12:40 pm,0.69 m,Bramble Cove,146.0,-43.19,TAS,2020-11-19T12:40:00+11:00
1,Fri 20 Nov,High,1:03 pm,0.65 m,Bramble Cove,146.0,-43.19,TAS,2020-11-20T13:03:00+11:00
6,Wed 25 Nov,High,7:53 pm,0.54 m,Bramble Cove,146.0,-43.19,TAS,2020-11-25T19:53:00+11:00
7,Thu 26 Nov,High,8:22 pm,0.57 m,Bramble Cove,146.0,-43.19,TAS,2020-11-26T20:22:00+11:00
8,Fri 27 Nov,High,8:58 pm,0.60 m,Bramble Cove,146.0,-43.19,TAS,2020-11-27T20:58:00+11:00
9,Sat 28 Nov,High,9:58 pm,0.61 m,Bramble Cove,146.0,-43.19,TAS,2020-11-28T21:58:00+11:00
0,Thu 19 Nov,Low,8:30 pm,0.06 m,Bramble Cove,146.0,-43.19,TAS,2020-11-19T20:30:00+11:00
1,Fri 20 Nov,Low,9:06 pm,0.12 m,Bramble Cove,146.0,-43.19,TAS,2020-11-20T21:06:00+11:00
6,Wed 25 Nov,Low,9:03 pm,0.53 m,Bramble Cove,146.0,-43.19,TAS,2020-11-25T21:03:00+11:00
7,Thu 26 Nov,Low,9:59 pm,0.55 m,Bramble Cove,146.0,-43.19,TAS,2020-11-26T21:59:00+11:00
8,Fri 27 Nov,Low,10:55 pm,0.57 m,Bramble Cove,146.0,-43.19,TAS,2020-11-27T22:55:00+11:00

In [98]:
clean_df.to_csv(r'./1128clean_bs4_tides_utc.csv', index = False, mode='a', header=True)